### ISSUE TITLE
RelayConnection and schema introspection

### ISSUE THREAD

**Issue by Bondza** [graphql-java-generator/graphql-maven-plugin-project#66] opened 2021-01-28 16:06 UTC
I'm using version 1.11.2 and am trying to use the `RelayConnection` directive. Where I use the `RelayConnection` directive I was expecting the schema to return a `Connection` type, but it only returns a list of objects.

With server code generated from this schema

```graphql
directive @RelayConnection on FIELD_DEFINITION

schema {
    query: Query
}

type Query {
    testConnection: [Test] @RelayConnection
}

type Test {
    id: ID!
    name: String
}
```

I see this in graphiql

![image](https://user-images.githubusercontent.com/1886115/106163124-1f641a80-6189-11eb-8a60-1d0b421a8f61.png)

I thought that maybe it graphiql just showed me the wrong schema, so I tried to run the following query in graphiql

```graphql
query Test {
  testConnection{
    edges{
      cursor
    }
    pageInfo{
      hasNextPage
    }
  }
}
```

But then I get these errors

```json
{
  "errors": [
    {
      "message": "Validation error of type FieldUndefined: Field 'edges' in type 'Test' is undefined @ 'testConnection/edges'",
      "locations": [
        {
          "line": 34,
          "column": 5
        }
      ],
      "extensions": {
        "classification": "ValidationError"
      }
    },
    {
      "message": "Validation error of type FieldUndefined: Field 'pageInfo' in type 'Test' is undefined @ 'testConnection/pageInfo'",
      "locations": [
        {
          "line": 37,
          "column": 5
        }
      ],
      "extensions": {
        "classification": "ValidationError"
      }
    }
  ]
}
```

I was expecting graphiql to say that `testConnection` returns a `TestConnection` object. Did I misunderstand how the directive is supposed to work or what it should generate?

**Comment by etienne-sf** [comment] 2021-01-29 13:15
Hello,

Yes, currently, there is an issue there. It works, but only when doing the stuff in two steps:

1. Generate the GraphQL schema
2. Use it


This can be done with having two steps in the pom.
Here is a sample:

```
			<plugin>
				<groupId>com.graphql-java-generator</groupId>
				<artifactId>graphql-maven-plugin</artifactId>
				<executions>
					<!-- These two executions allow to test the merge goal, then generate the code from the merged GraphQL schema file. 
						The graphql-maven-plugin-samples-allGraphQLCases-server project directly generates the code from the two (non merged) GraphQL 
						schema files -->
					<execution>
						<id>graphql-merge</id>
						<goals>
							<goal>generateGraphQLSchema</goal>
						</goals>
						<configuration>
							<!-- addRelayConnections will generate all the Relay Connection stuff (Node, Edge and Connection interfaces, and creating 
								the XxxEdge and XxxConnection interfaces or objects), for fields marked with the @RelatConnection directive. See the documentation 
								for more information -->
							<addRelayConnections>true</addRelayConnections>
							<schemaFileFolder>${basedir}/src/graphqls/</schemaFileFolder>
							<targetFolder>${basedir}/target/generated-resources/graphql-merge</targetFolder>
							<targetSchemaFileName>merged_schemas.graphqls</targetSchemaFileName>
						</configuration>
					</execution>
					<execution>
						<id>graphql-generateCode</id>
						<goals>
							<goal>generateClientCode</goal>
						</goals>
						<configuration>
...
						</configuration>
					</execution>
				</executions>
			</plugin>
```

**Comment by Bondza** [comment] 2021-01-29 19:33
Cool, I'll update them pom to try this. Thanks for the quick reply!

**Comment by etienne-sf** [comment] 2021-01-30 09:33
I'm still working on this one, to make things easy. You're questions has shown me that things are not that clear in the current version. 

I'll work on it this weekend.

**Comment by Bondza** [comment] 2021-01-31 19:56
This seems to generate the correct schema, but I'm having issues when I'm starting the app, I get an exception.

```
Caused by: java.io.FileNotFoundException: class path resource [merged_schemas.graphqls] cannot be opened because it does not exist
```

Does that mean that `merged_schemas.graphqls` isn't copied into the classpath? Can change a config to change this behavior?

**Comment by etienne-sf** [comment] 2021-01-31 21:03
Yes, I just found this one. 
And I'm really unhappy about that. I don't understand how it has been through my integration tests...

I'm just releasing the 1.12.1, that solves this issue. It will be available in some minutes.


Please that, with this version, you don't need to first generate the schema, then use this generated schema in the _generateServerCode_ task/goal.
Just use the _generateServerCode_ task/goal, exactly as you did in the first place
You can find a sample here: https://github.com/graphql-java-generator/graphql-maven-plugin-project/blob/master/graphql-maven-plugin-samples/graphql-maven-plugin-samples-Forum-server/pom.xml

Etienne

**Comment by Bondza** [comment] 2021-02-01 07:17
It's amazing that you have a fix for this already, thank you!!

I updated to 1.12.1 and reverted to just use the _generateServerCode_ goal. The generated schema looks good, but I'm still getting an exception when I try to start my app.

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field executor in com.graphql_java_generator.client.GraphQLConfiguration required a bean of type 'com.graphql_java_generator.client.QueryExecutor' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

The following candidates were found but could not be injected:
	- Bean method 'queryExecutor' in 'GraphQLAutoConfiguration' not loaded because auto-configuration 'GraphQLAutoConfiguration' was excluded


Action:

Consider revisiting the entries above or defining a bean of type 'com.graphql_java_generator.client.QueryExecutor' in your configuration.
```

I do not have a bean for `com.graphql_java_generator.client.QueryExecutor` and this worked in 1.11.2, did something change in 1.12 that means I need to create a bean for this? If I create a bean it works, but I'm not using the client. Can I configure this somehow?

**Comment by etienne-sf** [comment] 2021-02-01 07:39
Hum, hum. 

This error has been fixed 

Are you sure you use both the plug-in and the server-dependencies in version 1.12.1 ?
And that you did a proper ˋmvn clean` ?

**Comment by Bondza** [comment] 2021-02-02 12:49
I'm at bit slow to get back to you here. But the exception I got last is probably down to our setup so I'll see when I have time to figure that out.

But I did notice one other thing that changed. We have comments in our schema which was picked up as descriptions before, but they are gone since I updated to 1.12.1. Do you think this is config related to do I need to change the comments to make this work again?

**Comment by etienne-sf** [comment] 2021-02-03 19:57
I don't understand exactly what you mean by "comments in our schema which was picked up as descriptions". 

When is this "description" used ?



But here is how the RelayConnection works:

* the plug-in adds all the necessary stuff to manage the Relay Connection in the in memory schema 

* then it writes this updated schema , so that the GraphQL-Java has write to it at runtime. 

During this process, the comments are currently lost. I'll correct that, in the future. 

Étienne

**Comment by Bondza** [comment] 2021-02-08 10:03
Previously the schema in our comments would show up in GraphiQL for example. But it sounds like this may be because of how comments hare handled.

> During this process, the comments are currently lost. I'll correct that, in the future.

Also I noticed that connections are non-null in the generated schema. Is this configurable? I had a look at the [Connection spec](https://relay.dev/graphql/connections.htm#sec-Connection-Types) and at the [relay-examples](https://github.com/relayjs/relay-examples/blob/master/todo/data/schema.graphql#L15) and they don't seem to have non null connections.

Occasionally I would like to set the connection to `null` to indicate that there cannot exist any edges between nodes of the types.

**Comment by etienne-sf** [comment] 2021-02-08 16:14
Hum, you're right,

  From [this page](https://dev.to/mikemarcacci/intermediate-interfaces-generic-utility-types-in-graphql-50e8), the XXxxConnection field should be optional.

  I don't understand that, as it seems to me that the best way to check that is to have an empty edges list.
  With this that can be null, in order to check if the list is empty, the code has to check these three tests:
* The XxxConnection is non null, 
* The edges list is non null
* The edges list is not empty

Testing all these three conditions seems complex to me.
And your proposal _set the connection to null to indicate that there cannot exist any edges between nodes of the types_ seems to be an asumption that is only in your head.
This shows that it's hard to have a specification that is perfect... :)

So I'll change that.

Etienne

**Comment by Bondza** [comment] 2021-02-09 07:04
You're right that using the connection in this way is how I want to use it and not something mentioned in the spec. But given that the spec doesn't say that a connection must be non-null, I think it makes sense to leave it up to the user to use a null connection when it makes sense for them.

The downside of using the edges to do what I want is that I still have to create the `PageInfo` object, otherwise the query would return an error if the user selected the `pageInfo` and the edges were null.

I think you're right, creating a perfect specification sounds very hard :)

**Comment by etienne-sf** [comment] 2021-02-10 20:27
Can you check the 1.12.2 release, and confirm that all these issues are solved?

**Comment by Bondza** [comment] 2021-02-11 07:44
I've tried 1.12.2 and it fixed the issues I had. But I noticed two other issues.

First we had some default values on fields on an input type. These seem to get lost somewhere, I cannot see them in GraphiQL anymore. 
Second the application would not start when using the `@deprecated` directive on a field in an input object, I removed it and then it worked.

Should I create separate issues for these?

**Comment by mheidt** [comment] 2021-02-11 09:52
I can confirm, that @deprecated doesn't show in the documentation, when it's at an input object, but my application started nevertheless.

**Comment by etienne-sf** [comment] 2021-02-11 12:35
Yes, if you can create two new issues, and close this one, it would help.
:)

BTW, thanks for your feedback, I'll check that

Etienne

**Comment by etienne-sf** [comment] 2021-03-06 15:23
> First we had some default values on fields on an input type. These seem to get lost somewhere, I cannot see them in GraphiQL anymore.

My understanding of the the GraphQL spec, is that fields of input type may not have default values. You can check [the GraphQL spec here](file:///C:/APPLIRTE64/appli/Mes%20Sites%20Web/graphql%20(spec%20juin%202018)/spec.graphql.org/June2018/index.html#sec-Input-Object-Values], and this explanatation:

_The GraphQL Object type (ObjectTypeDefinition) defined above is inappropriate for re‐use here (as input object), **because Object types can contain fields that define arguments** or contain references to interfaces and unions, neither of which is appropriate for use as an input argument. For this reason, input objects have a separate type in the system._

> Second the application would not start when using the `@deprecated` directive on a field in an input object, I removed it and then it worked.

Again, I checked the GraphQL spec. Here is the definition of the _@deprecated_ annotation:

```
directive @deprecated(
  reason: String = "No longer supported"
) on FIELD_DEFINITION | ENUM_VALUE
```

Which means that the _@deprecated_ annotation is not valid on a field of an input object. To be valid on such a field, the _INPUT_FIELD_DEFINITION_ should be added to the _on_ list of the directive definition.

Etienne

**Closed** 2021-03-27 14:18 UTC
