### ISSUE TITLE
Release 1.0 empty in maven repo

### ISSUE THREAD

**Issue by viico** [graphql-java-generator/graphql-maven-plugin-project#2] opened 2019-12-16 14:43 UTC
Hi,

We would test your plugin to generate graphql client code but we have a maven dependency problem.

We use the last release (1.0) and we have this error : "Execution default-cli of goal com.graphql-java-generator:graphql-maven-plugin:1.0:graphql failed: Plugin com.graphql-java-generator:graphql-maven-plugin:1.0 or one of its dependencies could not be resolved: Failure to find com.graphql-java:graphql-java-spring-boot-starter-webmvc:jar:2019-11-16T19-22-11-31ab4f9 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced".

When we look in the repo maven we can't find any jar (https://repo1.maven.org/maven2/com/graphql-java-generator/graphql-maven-plugin-project/1.0/).

Is the release 1.0 works and if yes what am I doing wrong ?

**Comment by viico** [comment] 2019-12-16 14:56
I post this issue to soon, I think the problem is on the dependency "com.graphql-java:graphql-java-spring-boot-starter-webmvc:jar:2019-11-16T19-22-11-31ab4f9" which is not present on the repo maven (https://mvnrepository.com/artifact/com.graphql-java/graphql-java-spring-boot-starter-webmvc).

Where is the release 2019-11-16T19-22-11-31ab4f9 ?

**Comment by abedeoan** [comment] 2019-12-18 22:43
Hello viico, 
I had the same issue as you; one possible workaround is to change the version of the artifact to the latest known one from the Maven repository: 2019-06-24T11-47-27-31ab4f9.

**Comment by viico** [comment] 2019-12-19 08:22
Thanks abedeoan,

When I override the version of the artifact I got this error : 
`Error creating bean with name 'codeGenerator' defined in URL [jar:file:/C:/Users/pvll07191/.m2/repository/com/graphql-java-generator/graphql-maven-plugin-logic/1.0/graphql-maven-plugin-logic-1.0.jar!/com/graphql_java_generator/plugin/CodeGenerator.class]: Post-processing of merged bean definition failed; nested exception is java.lang.NoSuchMethodError: javax.annotation.Resource.lookup()Ljava/lang/String;`

I used 1.0 release with version 2019-06-24T11-47-27-31ab4f9 for graphql-java-spring-webmvc and graphql-java-spring-boot-starter-webmvc.
I had the same error when I tried to downgrade the maven plugin to the RC2 release.

I looked the javax.annotation.Resource class in my dependency and lookup() method is here, I didn't find ay other Resource class.

Is it works for you ? Any idea for this problem ?

**Comment by abedeoan** [comment] 2020-01-08 20:19
Hi viico, 

Etienne has fixed the dependency issue that you mentioned. 

Can you please confirm that the latest snapshot works for you, and then close this issue?

Happy New Year!

Amelia

**Comment by etienne-sf** [comment] 2020-01-08 21:02
Hello,

  The dependency version on 'graphql-java-spring-boot-starter-webmvc', that I used with the plugin seems to not exist any more.
The issue is corrected in the master.

I do some more corrections, then I do a new release.

**Comment by etienne-sf** [comment] 2020-01-26 13:55
Solved in the 1.2 version

**Closed by etienne-sf** 2020-01-26 13:55 UTC
