### ISSUE TITLE
POJO Class prefix

### ISSUE THREAD

**Issue by asmburns** [graphql-java-generator/graphql-maven-plugin-project#102] opened 2021-10-20 05:17 UTC
How can i specify prefix on generated classes? 
Example: 
type Client 
generates into 
public class Client 

But i want to "mark" this class with prefix 
public class GqlClient

**Comment by etienne-sf** [comment] 2021-10-20 17:58
Currently, there is no way to do that. 

Someone already asked for that, but didn't answer to my question : why would you want to do that ?

Étienne

**Comment by etienne-sf** [comment] 2021-10-20 18:14
BTW, you can update the templates (I'll give you the names once I'm in front of my computer, if you're interested). 

By doing this, you can change everything that is generated. 

(But I'm still interested in the reason why you want to do this)

**Comment by agesenm-ELS** [comment] 2022-10-11 14:28
Hi @etienne-sf 

Here is one reason to add support for prefixes and suffixes for input object, types, enums, etc. 
 
 We are trying to replace a legacy code generator with graphql-maven-plugin-project. The old generator is used a naming scheme with a suffix for input objects and types, where for example the type `Droid` would be named `DroidGraphQLType` (similarly for interfaces and enums). There are thousands of existing usages of these classes, and we do not want to migrate all existing code, especially because there are existing classes (domain objects, and enums) used in the data fetchers, with the same class name as those that would be generated without a suffix.

We tried if we could solve the problem by changing the generated class name in `object_type.vm.java` but the filename and constructor must also changed, and that is done outside the template.

If we made a pull request adding support for configuring a prefix and suffix for the generated class names, would you consider merging it?

Best,
Mikkel

**Comment by etienne-sf** [comment] 2022-10-11 17:01
Of course!

I would be glad to integrate a PR on this subject
🙂

I'm currently working on the 2.x branch. I'll report the PR on the future 2.x branch.

**Comment by agesenm-ELS** [comment] 2022-10-13 13:30
Hi Étienne

The [pull request](https://github.com/graphql-java-generator/graphql-maven-plugin-project/pull/155) is ready for review.

The are a few [failing tests](https://github.com/agesenm-ELS/graphql-maven-plugin-project/pull/1/checks?check_run_id=8869517616), but that looks more like an infrastructure problem than actual failures caused by the change. 

Best,
Mikkel

**Comment by etienne-sf** [comment] 2022-11-06 17:54
Released in the 1.18.8 version

**Closed by etienne-sf** 2022-11-06 17:54 UTC
