### ISSUE TITLE
Default target folder based on <directory>target</directory

### ISSUE THREAD

**Issue by heyarny** [graphql-java-generator/graphql-maven-plugin-project#218] opened 2024-07-15 08:38 UTC
Hi,

we are using a different target folder and as of now we have to override our default hardcoded "target" folder.
```
    <configuration>
        <targetResourceFolder>${project.build.directory}/generated-resources/graphql-maven-plugin</targetResourceFolder>
        <targetSourceFolder>${project.build.directory}/generated-sources/graphql-maven-plugin</targetSourceFolder>
    </configuration>
```

It would be more convenient to change the target globally in one place on maven and not having all plugins have their own target folders.

Greetings

**Comment by etienne-sf** [comment] 2024-07-16 08:23
Hello, 

If I understand correctly: you have several executions of the plugin in your build, and you would like to configure the folders only once. 
Correct ?

If yes, please note that maven gives you this ability through the plugin management capability. This allows you to define the plugin version and a default configuration for the plugins. 

Please also note that it's important to separate the folder where the source is generated by plugin execution. There are tests that compare the generated files and the source GraphQL schema, to check if the generation should occur. 

Étienne

**Comment by heyarny** [comment] 2024-07-25 05:48
@etienne-sf 
Yes, usually many plugins follow the <build.output>target-folder</build.output> setting. But the graphql-plugin is ignoring our custom set target.

**Comment by heyarny** [comment] 2024-07-25 06:09
Updated the title to be more clear.

Usually we set `<build.output>` which is a global setting for the whole project. Not sure why graphql-maven-plugin still should prefer to use their own "target" default.

**Comment by etienne-sf** [comment] 2024-07-25 09:04
These are not the same. 

The targetResourceFolder and targetSourceFolder:
* should be sub-folders of the <build><directory> folder 
* should be undefined when using only one GraphQL server (and let the default value be used)
* must be a plugin parameter, so that their value are different when generating a client that attacks more than one GraphQL server 


To ensure that these two plugin parameters point to a sub-folder of the <build><directory> folder, you should use this maven placeholder: ${project.build.directory}

Étienne

**Comment by heyarny** [comment] 2024-08-25 11:09
No idea what you mean. I don't want to override default settings via ${project.build.directory}.

The default way to change the default build target is by setting <build><directory>target-folder</directory></build>.
Yet the GraphQL plugin is still preferring its own "target" I have no idea why and where it is getting its target from.

**Comment by etienne-sf** [comment] 2024-08-29 17:49
Ah, Ok, I think I understand what you're asking.

Your maven build folder is no more ./target.
But the issue here is that the graphql plugin still generates the code into the ./target/xxx folder.

So the issue is that the plugin should use the maven configuration.

Is that correct ?


BTW, this is quite unusual. Why did you change the target folder ?
(I guess this plugin is not the only one that has issues with this change)

Etienne

**Comment by heyarny** [comment] 2024-09-16 21:41
@etienne-sf it is one of few we could identify.
We use it in our development setup to separate certain builds to certain targets to keep them separated.

**Comment by etienne-sf** [comment] 2024-09-25 06:36
Hello

This has been released in the last version

Étienne

**Closed** 2024-09-25 06:37 UTC
